<div class="game-controls">
    <div id="guessed-letters"></div>
    <div id="wrong-letters"></div>
    <a href="<?php echo $this->url('application/default', ['controller' => 'game', 'action' => 'pause']); ?>" class="btn btn-warning" id="pause-game"><i class="fa fa-pause"></i> Spiel unterbrechen</a>
    <a href="<?php echo $this->url('application/default', ['controller' => 'game', 'action' => 'forfeit']); ?>" class="btn btn-danger" id="pause-game"><i class="fa fa-flag"></i> Spiel aufgeben</a>
</div>
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/application/game.js'));