<h1>Viele Wörter</h1>
<?php
/** @var \Application\Entity\Word[] $words */
$words = $this->words;

/** @var int $pageCount amount of pages */
$pageCount = $this->pageCount;
$currentPage = $this->currentPage;

$isAdmin = ($this->identity() instanceof \Application\Entity\User && $this->identity()->getRole() == 'admin');

/** @var \Application\Form\WordSearchForm $form */
$form = $this->form;

$urlParameters = [];
$orderBy = $this->orderBy;
$direction = $this->direction;
$query = $this->query;

if ($orderBy != null) {
    $urlParameters['o'] = $orderBy;
}

if ($direction != null) {
    $urlParameters['d'] = $direction;
}

if ($query != null) {
    $urlParameters['q'] = $query;
}
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->btFormRow($form->get('q')); ?>
<?php echo $this->btFormRow($form->get('o')); ?>
<?php echo $this->btFormRow($form->get('d')); ?>
<?php echo $this->btFormRow($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<?php if ($isAdmin): ?>
    <br>
    <a href="<?php echo $this->url('application/word', ['action' => 'add']); ?>" class="btn btn-primary btn-lg">
        <i class="fa fa-plus-circle"></i> Wort hinzufügen
    </a>
<?php endif; ?>

<nav class="word-list">
    <ul class="pagination">
        <li <?php if ($currentPage <= 1): ?>class="disabled"<?php endif; ?>>
            <a
                href="<?php if ($currentPage > 1) {
                    echo $this->url('application/words', [], ['query' => array_merge(['p' => $currentPage - 1], $urlParameters)]);
                } ?>#"
                aria-label="Previous"
                >
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <?php for ($i = 1; $i <= $pageCount; $i++): ?>
            <li <?php if ($currentPage == $i): ?> class="active" <?php endif; ?>>
                <a href="<?php echo $this->url('application/words', [], ['query' => array_merge(['p' => $i], $urlParameters)]); ?>">
                    <?php echo $i; ?>
                </a>
            </li>
        <?php endfor; ?>
        <li <?php if ($currentPage >= $pageCount): ?>class="disabled"<?php endif; ?>>
            <a
                href="<?php if ($currentPage < $pageCount) {
                    echo $this->url('application/words', [], ['query' => array_merge(['p' => $currentPage + 1], $urlParameters)]);
                } ?>#"
                aria-label="Next"
                >
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
<div class="word-list-container">
    <?php
    $lastFirstLetter = null;
    $letters = [];
    foreach ($words as $word) {
        $firstLetter = $word->getFirstLetter();
        $letters[$firstLetter][] = $word;
    }
    foreach ($letters as $firstLetter => $words):
        if ($this->orderBy == 'word'):
        ?>
        <div class="subtitle bg-primary">
            <?php echo $firstLetter; ?>
        </div>
        <?php endif; ?>
        <?php foreach ($words as $word): ?>
        <div class="entry">
            <div class="word">
                <?php echo $word->getWord(); ?>
            </div>
            <div class="slide-down">
                <span class="modification-times">
                    <?php
                    ?>
                    <small>
                        Hinzugefügt: <abbr
                            title="<?php echo $word->getCreatedAt()->format('d.m.Y H:i'); ?>"><?php echo $this->timeAgo($word->getCreatedAt()); ?></abbr>
                    </small>
                    <br>
                    <small>
                        Zuletzt bearbeitet: <abbr
                            title="<?php echo $word->getCreatedAt()->format('d.m.Y H:i'); ?>"><?php echo $this->timeAgo($word->getUpdatedAt()); ?></abbr>
                    </small>
                </span>

                <?php if ($isAdmin): ?>
                <div class="links">
                    <div class="btn-group">
                        <a class="btn btn-primary btn-xs"
                           href="<?php echo $this->url('application/words', ['action' => 'edit', 'id' => $word->getId(),], []); ?>">
                            <i class="fa fa-edit"></i> Bearbeiten
                        </a>
                        <a class="btn btn-danger btn-xs">
                            <i class="fa fa-trash-o"></i> Löschen
                        </a>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>

    <?php
    endforeach;
    ?>
</div>
<nav class="word-list">
    <ul class="pagination">
        <li <?php if ($currentPage <= 1): ?>class="disabled"<?php endif; ?>>
            <a
                href="<?php if ($currentPage > 1) {
                    echo $this->url('application/words', [], ['query' => array_merge(['p' => $currentPage - 1], $urlParameters)]);
                } ?>#"
                aria-label="Previous"
                >
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <?php for ($i = 1; $i <= $pageCount; $i++): ?>
            <li <?php if ($currentPage == $i): ?> class="active" <?php endif; ?>>
                <a href="<?php echo $this->url('application/words', [], ['query' => array_merge(['p' => $i], $urlParameters)]); ?>">
                    <?php echo $i; ?>
                </a>
            </li>
        <?php endfor; ?>
        <li <?php if ($currentPage >= $pageCount): ?>class="disabled"<?php endif; ?>>
            <a
                href="<?php if ($currentPage < $pageCount) {
                    echo $this->url('application/words', [], ['query' => array_merge(['p' => $currentPage + 1], $urlParameters)]);
                } ?>#"
                aria-label="Next"
                >
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

<?php if ($isAdmin): ?>
    <a href="<?php echo $this->url('application/word', ['action' => 'add']); ?>" class="btn btn-primary btn-lg">
        <i class="fa fa-plus-circle"></i> Wort hinzufügen
    </a>
<?php endif; ?>
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/application/word.js'));