<div class="col-xs-12 col-sm-6">
    <?php
    /** @var \Application\Form\WordForm $form */
    $form = $this->form;
    ?>
    <?php echo $this->form()->openTag($form); ?>
    <?php if ($this->loginFailed): ?>
        <div class="alert alert-warning">
            <strong>Anmeldung Fehlgeschlagen</strong> Bitte Benutzernamen und Passwort prüfen!
        </div>
    <?php endif; ?>
    <?php echo $this->btFormRow($form->get('username')); ?>
    <?php echo $this->btFormRow($form->get('password')); ?>
    <?php echo $this->btFormRow($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
