<h1 class="page-header">Registrieren</h1>
<div class="col-xs-12 col-sm-6">
    <?php
    /** @var \Application\Form\UserForm $form */
    $form = $this->form;
    ?>
    <?php echo $this->form()->openTag($form); ?>
    <?php if ($this->userNameConflict): ?>
        <div class="alert alert-danger">
            <strong>Der gewählte Benutzername ist leider bereits vergeben.</strong>
        </div>
    <?php endif; ?>
    <?php echo $this->btFormRow($form->get('username')); ?>
    <?php echo $this->btFormRow($form->get('email')); ?>
    <?php echo $this->btFormRow($form->get('password')); ?>
    <?php echo $this->btFormRow($form->get('confirmPassword')); ?>
    <?php echo $this->btFormRow($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
