<div class="jumbotron">
    <h1>Willkommen bei Hangman</h1>
    <p>Du kannst gleich losspielen oder dir die Wörter ansehen:</p>
    <a href="<?php echo $this->url('application/game'); ?>" class="btn btn-success btn-lg"><i class="fa fa-gamepad"></i> Zum Spiel</a>
    <a href="<?php echo $this->url('application/words'); ?>" class="btn btn-info btn-lg"><i class="fa fa-list"></i> Zur Wörterliste</a>
</div>