<div class="jumbotron">
    <h1>Willkommen bei Hangman</h1>
    <p>Um mitzuspielen, logge dich ein!</p>
    <p>
        <a href="<?php echo $this->url('application/user', ['action' => 'login']); ?>" class="btn btn-primary btn-lg"><i class="fa fa-sign-in"></i> Login</a>
        oder
        <a href="<?php echo $this->url('application/user', ['action' => 'register']); ?>" class="btn btn-default btn-lg"><i class="fa fa-plus-circle"></i> Neu Registrieren</a>
    </p>
</div>